/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE DJI_POSE_STAMPED PACKING
package com.MAVLink.dji_icg;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
* Set position in pose stamped format.
*/
public class msg_dji_pose_stamped extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_DJI_POSE_STAMPED = 50004;
    public static final int MAVLINK_MSG_ID_DJI_POSE_STAMPED_CRC = 70;
    public static final int MAVLINK_MSG_LENGTH = 66;
    private static final long serialVersionUID = MAVLINK_MSG_ID_DJI_POSE_STAMPED;


      
    /**
    * Position
    */
    public double position[] = new double[3];
      
    /**
    * Orientation
    */
    public double orientation[] = new double[4];
      
    /**
    * Timestamp - Seconds since epoch
    */
    public long sec;
      
    /**
    * Timestamp since epoch = sec + nsec * 10^-9
    */
    public long nsec;
      
    /**
    * System ID
    */
    public short target_system;
      
    /**
    * See DJI_TOPIC_NAME enum
    */
    public short topic_name;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_DJI_POSE_STAMPED;
        packet.crc_extra = MAVLINK_MSG_ID_DJI_POSE_STAMPED_CRC;
              
        
        for (int i = 0; i < position.length; i++) {
            packet.payload.putDouble(position[i]);
        }
                    
              
        
        for (int i = 0; i < orientation.length; i++) {
            packet.payload.putDouble(orientation[i]);
        }
                    
              
        packet.payload.putUnsignedInt(sec);
              
        packet.payload.putUnsignedInt(nsec);
              
        packet.payload.putUnsignedByte(target_system);
              
        packet.payload.putUnsignedByte(topic_name);
        
        return packet;
    }

    /**
    * Decode a dji_pose_stamped message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
         
        for (int i = 0; i < this.position.length; i++) {
            this.position[i] = payload.getDouble();
        }
                
              
         
        for (int i = 0; i < this.orientation.length; i++) {
            this.orientation[i] = payload.getDouble();
        }
                
              
        this.sec = payload.getUnsignedInt();
              
        this.nsec = payload.getUnsignedInt();
              
        this.target_system = payload.getUnsignedByte();
              
        this.topic_name = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_dji_pose_stamped(){
        msgid = MAVLINK_MSG_ID_DJI_POSE_STAMPED;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_dji_pose_stamped(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_DJI_POSE_STAMPED;
        unpack(mavLinkPacket.payload);
    }

                
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_DJI_POSE_STAMPED - sysid:"+sysid+" compid:"+compid+" position:"+position+" orientation:"+orientation+" sec:"+sec+" nsec:"+nsec+" target_system:"+target_system+" topic_name:"+topic_name+"";
    }
}
        