/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE DJI_ACTION_COMMAND PACKING
package com.MAVLink.dji_icg;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
* Simple commands for the drone.
*/
public class msg_dji_action_command extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_DJI_ACTION_COMMAND = 50005;
    public static final int MAVLINK_MSG_ID_DJI_ACTION_COMMAND_CRC = 2;
    public static final int MAVLINK_MSG_LENGTH = 13;
    private static final long serialVersionUID = MAVLINK_MSG_ID_DJI_ACTION_COMMAND;


      
    /**
    * Timestamp - Seconds since epoch
    */
    public long sec;
      
    /**
    * Timestamp since epoch = sec + nsec * 10^-9
    */
    public long nsec;
      
    /**
    * See DJI_ACTION enum
    */
    public int action;
      
    /**
    * System ID
    */
    public short target_system;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_DJI_ACTION_COMMAND;
        packet.crc_extra = MAVLINK_MSG_ID_DJI_ACTION_COMMAND_CRC;
              
        packet.payload.putUnsignedInt(sec);
              
        packet.payload.putUnsignedInt(nsec);
              
        packet.payload.putInt(action);
              
        packet.payload.putUnsignedByte(target_system);
        
        return packet;
    }

    /**
    * Decode a dji_action_command message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.sec = payload.getUnsignedInt();
              
        this.nsec = payload.getUnsignedInt();
              
        this.action = payload.getInt();
              
        this.target_system = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_dji_action_command(){
        msgid = MAVLINK_MSG_ID_DJI_ACTION_COMMAND;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_dji_action_command(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_DJI_ACTION_COMMAND;
        unpack(mavLinkPacket.payload);
    }

            
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_DJI_ACTION_COMMAND - sysid:"+sysid+" compid:"+compid+" sec:"+sec+" nsec:"+nsec+" action:"+action+" target_system:"+target_system+"";
    }
}
        