/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE DJI_LOG PACKING
package com.MAVLink.dji_icg;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
* Send a part of the file.
*/
public class msg_dji_log extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_DJI_LOG = 50008;
    public static final int MAVLINK_MSG_ID_DJI_LOG_CRC = 252;
    public static final int MAVLINK_MSG_LENGTH = 254;
    private static final long serialVersionUID = MAVLINK_MSG_ID_DJI_LOG;


      
    /**
    * System ID (0 for broadcast).
    */
    public short target_system;
      
    /**
    * Variable length message. The length is defined by the remaining message length when subtracting the header and other fields.
    */
    public short log_message[] = new short[253];
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_DJI_LOG;
        packet.crc_extra = MAVLINK_MSG_ID_DJI_LOG_CRC;
              
        packet.payload.putUnsignedByte(target_system);
              
        
        for (int i = 0; i < log_message.length; i++) {
            packet.payload.putUnsignedByte(log_message[i]);
        }
                    
        
        return packet;
    }

    /**
    * Decode a dji_log message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.target_system = payload.getUnsignedByte();
              
         
        for (int i = 0; i < this.log_message.length; i++) {
            this.log_message[i] = payload.getUnsignedByte();
        }
                
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_dji_log(){
        msgid = MAVLINK_MSG_ID_DJI_LOG;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_dji_log(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_DJI_LOG;
        unpack(mavLinkPacket.payload);
    }

        
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_DJI_LOG - sysid:"+sysid+" compid:"+compid+" target_system:"+target_system+" log_message:"+log_message+"";
    }
}
        