/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE DJI_FTP PACKING
package com.MAVLink.dji_icg;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
* Send a part of the file.
*/
public class msg_dji_ftp extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_DJI_FTP = 50002;
    public static final int MAVLINK_MSG_ID_DJI_FTP_CRC = 113;
    public static final int MAVLINK_MSG_LENGTH = 254;
    private static final long serialVersionUID = MAVLINK_MSG_ID_DJI_FTP;


      
    /**
    * Sequence number.
    */
    public int sequence;
      
    /**
    * System ID (0 for broadcast).
    */
    public short target_system;
      
    /**
    * Id of the file.
    */
    public short file_id;
      
    /**
    * Variable length payload. The length is defined by the remaining message length when subtracting the header and other fields.
    */
    public short payload[] = new short[250];
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_DJI_FTP;
        packet.crc_extra = MAVLINK_MSG_ID_DJI_FTP_CRC;
              
        packet.payload.putUnsignedShort(sequence);
              
        packet.payload.putUnsignedByte(target_system);
              
        packet.payload.putUnsignedByte(file_id);
              
        
        for (int i = 0; i < payload.length; i++) {
            packet.payload.putUnsignedByte(payload[i]);
        }
                    
        
        return packet;
    }

    /**
    * Decode a dji_ftp message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.sequence = payload.getUnsignedShort();
              
        this.target_system = payload.getUnsignedByte();
              
        this.file_id = payload.getUnsignedByte();
              
         
        for (int i = 0; i < this.payload.length; i++) {
            this.payload[i] = payload.getUnsignedByte();
        }
                
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_dji_ftp(){
        msgid = MAVLINK_MSG_ID_DJI_FTP;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_dji_ftp(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_DJI_FTP;
        unpack(mavLinkPacket.payload);
    }

            
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_DJI_FTP - sysid:"+sysid+" compid:"+compid+" sequence:"+sequence+" target_system:"+target_system+" file_id:"+file_id+" payload:"+payload+"";
    }
}
        