/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* An enum for different simple commands for the drone.
*/
public class DJI_ACTION {
   public static final int DJI_ACTION_TAKE_OFF = 0; /* Take off command. | */
   public static final int DJI_ACTION_LAND = 1; /* Land command. | */
   public static final int DJI_ACTION_FLY_TRAJECTORY = 2; /* Command to fly the trajectory. | */
   public static final int DJI_ACTION_HOVER = 3; /* Command to hover. | */
   public static final int DJI_ACTION_SYNC_TIME = 4; /* Uses the time from the message to sync the clocks. | */
   public static final int DJI_ACTION_ENUM_END = 5; /*  | */
}
            