/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* An enum holding the combinations of topic names and header frames.
*/
public class DJI_TOPIC_NAME {
   public static final int DJI_TOPIC_NAME_SETPOINT = 0; /* Setpoint. | */
   public static final int DJI_TOPIC_NAME_DRONE_POSITION = 1; /* Drone position. | */
   public static final int DJI_TOPIC_NAME_RUINA_IN_PARIETE = 2; /* TEST - Crash into a wall | */
   public static final int DJI_TOPIC_NAME_ENUM_END = 3; /*  | */
}
            