/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* Enumeration for states of low battery extent
*/
public class MAV_BATTERY_CHARGE_STATE {
   public static final int MAV_BATTERY_CHARGE_STATE_UNDEFINED = 0; /* Low battery state is not provided | */
   public static final int MAV_BATTERY_CHARGE_STATE_OK = 1; /* Battery is not nearly empty, normal operation | */
   public static final int MAV_BATTERY_CHARGE_STATE_LOW = 2; /* Battery state is low, warn and monitor close | */
   public static final int MAV_BATTERY_CHARGE_STATE_CRITICAL = 3; /* Battry state is critical, return / abort immediately | */
   public static final int MAV_BATTERY_CHARGE_STATE_EMERGENCY = 4; /* Battry state is too low for ordinary abortion, fastest possible emergency stop preventing damage | */
   public static final int MAV_BATTERY_CHARGE_STATE_FAILED = 5; /* Battry failed, damage unavoidable | */
   public static final int MAV_BATTERY_CHARGE_STATE_UNHEALTHY = 6; /* Battry is diagnosed to be broken or an error occurred, usage is discouraged / prohibited | */
   public static final int MAV_BATTERY_CHARGE_STATE_ENUM_END = 7; /*  | */
}
            